global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'llm-micro-services'
    metrics_path: '/metrics'
    static_configs:
      - targets:
        - 'host.docker.internal:8081' # Gateway Service
        - 'host.docker.internal:8001' # Knowledge Service
        - 'host.docker.internal:8002' # RAG Engine
        - 'host.docker.internal:8003' # Auth Service
        - 'host.docker.internal:8004' # Vector Service (Standalone Metrics Port)
        - 'host.docker.internal:8005' # Cost Service (Standalone Metrics Port)
